spring:
  datasource:
    url: jdbc:mysql://home.mytest.com:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #schema: classpath:db/schema.sql
    #没有生效
    data: classpath:db/data.sql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  # 去掉html的校验
  thymeleaf:
    cache: false
    mode: LEGACYHTML5